### ISSUE TITLE
Windows redownload fails?

### ISSUE THREAD

**Issue by TrentBartlem** [maestrodev/puppet-wget#35]
Could not evaluate: Could not find command 'test'

Presumably due to $unless_test in /fetch.pp ?

**Comment by richardwadsworth** [comment]
I have the same error.  it's actually this line that is failing

$unless_test = "test -s ${destination}"

**Comment by carlossg** [comment]
so what would work in windows for the unless test? I don't have access to a windows box

* `exist ${destination}`
* `cmd -D exist ${destination}`
* `if exist ${destination} true else false`
* ?

**Comment by carlossg** [comment]
Fixed in #54
