### ISSUE TITLE
no way to disable file backup

### ISSUE THREAD

**Issue by duskglow** [maestrodev/puppet-wget#39]
Can you please support an option to turn file backup off.

I am trying to download a 390M file, and every time it changes it tries to back it up to the filestore and fails.  I don't really care if it does, because it's being pulled from artifactory.  We are using r10k so I would have to actually fork the module to make that work, and I don't really want to do that.  It should be a simple matter of adding the backup option to the File object and exposing it as a parameter.

Thanks. :)

**Comment by carlossg** [comment]
Can you submit a PR?

**Comment by duskglow** [comment]
done.
