### ISSUE TITLE
specify http_proxy information as wget::fetch attribute

### ISSUE THREAD

**Issue by rauchrob** [maestrodev/puppet-wget#45]
Currently, HTTP-Proxy information for `wget::fetch`  can be specified by setting the top scope variables `$::http_proxy` and/or `$::https_proxy`. However, I think it is generally bad practice for a Puppet module to rely on the presence of certain global variables (if every module would do it that way, it would be a totally mess). 

In my opinion, this piece of information should be specified as parameter for `wget::fetch`.

**Comment by carlossg** [comment]
see #61
