### ISSUE TITLE
feature: Do not manage wget package

### ISSUE THREAD

**Issue by mkrakowitzer** [maestrodev/puppet-wget#55]
I have a use case where I want to use this module as a non root user. The yum provider can not be used as a non root user: "Error: Could not prefetch package provider 'yum': The yum provider can only be used as root."

Would you be open to me submitting a pull request 'manage_package' which would allow the package management to be disabled?

**Comment by carlossg** [comment]
as long as it keeps backwards compatibility it is ok

**Comment by mkrakowitzer** [comment]
Thanks

**Comment by carlossg** [comment]
see #57
