### ISSUE TITLE
Errors when enabling strict_variables

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [maestrodev/puppet-wget#62]
This module seems to use three global variables which puppet 4 will complain about if `strict_variables` is `true`:

* http_proxy
* https_proxy
* schedule (_manifests/fetch.pp:99_)

As a workaround I have to add the following to site.pp:

```puppet
$http_proxy = undef
$https_proxy = undef
$schedule = undef
```

Related to #45

**Comment by carlossg** [comment]
see #61
