### ISSUE TITLE
Error: Invalid parameter unless on Wget::Fetch

### ISSUE THREAD

**Issue by drmarconi** [maestrodev/puppet-wget#71]
Hi,

It seems that the Puppet Forge code is slightly out of date compared to GitHub. The 'unless' parameter is not available when using the module from the Forge, resulting in error:

Error: Invalid parameter unless on Wget::Fetch

Please could the forge module be updated?

Thanks.

**Comment by aranc23** [comment]
It would be convenient if the puppet forge module was updated. I encountered this issue when trying to use the module with jlambert121/kibana

**Comment by carlossg** [comment]
1.7.2 released

**Comment by drmarconi** [comment]
Thank you for the quick turnaround! Much appriciated.
